version: "3"
 
volumes:
  local_postgres_data: {}
 
services:
  web:
    build: ./back
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./back:/app
      - /app/RemixedRecipes/bin
      - /app/RemixedRecipes/obj
    depends_on:
      - db
 
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
 
  client:
    build: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
